name: Tweet to Twitter
on:
  schedule:
    - cron: "0 7 * * *"     # runs at 07:00 UTC everyday
    - cron: "0 8-23 26 5 *" # runs every hour from 08:00 to 23:00 UTC on May 26th
    - cron: "0 0-6 27 5 *"  # runs every hour from 00:00 to 06:00 UTC on May 27th
    - cron: "0 8-23 30 6 *" # runs every hour from 08:00 to 23:00 UTC on June 30th
    - cron: "0 0-6 1 7 *"   # runs every hour from 00:00 to 06:00 UTC on July 1st
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Setup tweepy
        run: pip install tweepy
      - name: Execute py script
        run: | 
          python main.py
        env:
          API_KEY: ${{ secrets.TWITTER_API_KEY }}
          API_KEY_SECRET: ${{ secrets.TWITTER_API_KEY_SECRET }}
          ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
